#!/bin/bash

nums=(3.14 2.718 0.57721 4.6692) # create an array

echo "pi : ${nums[0]}"

nums[4]=1.618 # define a new element by index

echo "GR : ${nums[4]}"

nums+=(1 7) # append 2 new elements

for i in ${nums[*]}; do #print all values in array
    echo $i
done

for i in ${nums[@]}; do #print all indices
    echo $i
done

echo "Array Length : ${#nums[@]}"
echo "Index 3 length: ${#nums[3]}"

sorted_nums=($(for i in "${nums[@]}"; do
    echo $i
done | sort))

for i in ${sorted_nums[*]}; do #print all indices
    echo $i
done

unset "sorted_numes[1]" # delete index 1
unset sorted_nums # delete array
