#!/bin/bash

read -p "What is your name? " name
read -p "How old are you? " age

echo "Hello $name"
if [ $age -ge 16 ]
then
    echo "You can drive"
elif [ $age -eq 15 ]
then
    echo "You can drive next year"
else
    echo "You cannot drive"
fi

