#!/bin/bash

read -p "Enter a number: " num 

if ((num == 10)); then
    echo "Your number equals 10"
fi

if ((num > 10)); then
    echo "It is greater than 10"
else
    echo "It is less than 10"
fi

if (( ((num % 2)) == 0)); then
    echo "It is even"
else
    echo "It is odd"
fi

if (( ((num > 0)) && ((num < 11)) )); then
    echo "$num is between 1 - 10"
fi

## Create file, then open in vim (silly example)
#touch samp_file && vim samp_file

# Check is directory exists, mkdir if it does not already exist
#[ -d samp_dir ] || mkdir samp_dir
